name: create-builder

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - "containerfiles/**"

jobs:
  create-builder:
    name: create-builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Publish
        run: |
          pack builder create yunarta/cnb-mobilesolutionworks-builder:oracle9 --config ./builder.toml